package dao.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import dao.PhotoText;
import dao.Test;

import dao.greendao.PhotoTextDao;
import dao.greendao.TestDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig photoTextDaoConfig;
    private final DaoConfig testDaoConfig;

    private final PhotoTextDao photoTextDao;
    private final TestDao testDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        photoTextDaoConfig = daoConfigMap.get(PhotoTextDao.class).clone();
        photoTextDaoConfig.initIdentityScope(type);

        testDaoConfig = daoConfigMap.get(TestDao.class).clone();
        testDaoConfig.initIdentityScope(type);

        photoTextDao = new PhotoTextDao(photoTextDaoConfig, this);
        testDao = new TestDao(testDaoConfig, this);

        registerDao(PhotoText.class, photoTextDao);
        registerDao(Test.class, testDao);
    }
    
    public void clear() {
        photoTextDaoConfig.clearIdentityScope();
        testDaoConfig.clearIdentityScope();
    }

    public PhotoTextDao getPhotoTextDao() {
        return photoTextDao;
    }

    public TestDao getTestDao() {
        return testDao;
    }

}
